# This configuration can be changed from this https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
# I will be putting comments on certain places where necessary

site_name: WADL Project Documentation
repo_url: https://github.com/codersforcauses/wadl/

# This uri refers to the github path to edit, change this if you branch is different in name
edit_uri: edit/main/docs/docs/
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)" # below here is a palette for light mode
    primary: yellow
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"  # below here is a palette for dark mode
    primary: yellow
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

  logo: images/TextlessTransparentLogo.png
  favicon: images/TextlessTransparentLogo.png
  features: # Refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
      - navigation.instant
  #   - navigation.tabs
plugins:
  - search
  - mermaid2:
      version: 8.8.2
      arguments:
        theme: white # change this as you see fit - ["white", "dark"]
      
  # This is the PDF Generator of the documentation
  # More information here  https://github.com/orzih/mkdocs-with-pdf
  # note at this current moment, to use this feature, the following must be met
  # - Relative Path only with images
  # - Mermaid Markdown doesn't render at the moment in PDF
  - with-pdf:
      author: Dominic Cain
      cover_title: WADL Project Documentation
      cover_logo: ./docs/images/TextlessTransparentLogo.png
      enabled_if_env: ENABLE_PDF_EXPORT # This prevents generation of pdf when using `mkdocs serve` because it takes a long time. This will however generate the PDF when the environment variable is setup OR in the github action

# These are markdown extensions I have included that makes the documentation look nicer
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

# This is the extra javascript included in the documentation
extra_javascript:
  - https://unpkg.com/mermaid@8.8.2/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# This is where you adjust the hierarchy if the documentation
# You can erase this if you want. If you erase this, Mkdocs will alphabetically sort your documentation
nav:
- Home: index.md
- Installation Guide: installation-guide.md
- Components: components.md