name: Constant Integration for JavaScript
on:
  pull_request:
    type: [opened, edited]
    paths:
      - '**.js'
      - '**.cjs'
      - '**.mjs'
      - '**.vue'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      - name: Setup Node with yarn
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Run ESLint
        uses: wearerequired/lint-action@66e2f9c9bf05b7aca19dbb59aebad95da5ddc537
        with:
          eslint: true
          neutral_check_on_warning: true
